# Generated by Django 5.2.9 on 2026-02-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_location_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='catalogue.locality'),
        ),
    ]
