# Generated by Django 5.2.9 on 2026-02-11 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_location_locality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artist')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.type')),
            ],
            options={
                'db_table': 'artist_type',
            },
        ),
        migrations.CreateModel(
            name='ArtistTypeShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.artisttype')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.show')),
            ],
            options={
                'db_table': 'artist_type_show',
            },
        ),
        migrations.CreateModel(
            name='Representation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representations', to='catalogue.location')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representations', to='catalogue.show')),
            ],
            options={
                'db_table': 'representations',
            },
        ),
    ]
