# Generated by Django 5.2.9 on 2026-02-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
